In [39]:
import numpy as np
a=np.matrix([1,2,3,4,5,6,7,8,9]).reshape(3,3)
b=np.matrix([9,8,7,6,5,4,3,2,1]).reshape(3,3)
c=np.hstack((a,b))
d=np.vstack((a,b))
print(c)


[[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]
